import {resolve} from 'node:path';
import {mkdir,writeFile,access} from 'node:fs/promises';
export const WORKSTREAMS:Record<string,string[]>={Brief:['Goals','Constraints','Acceptance'],ID:['Research','Concepts','Form CAD','Handoff'],ME:['Research','Packaging','Detailed CAD','Drawings'],EE:['Research','Architecture','Schematic','PCB & harness'],SW:['Research','Interfaces','Implementation','Tests'],MFG:['Research','Process','BOM','Assembly'],SIM:['Research','Question','Model','Experiment','Feedback']};
export type Project={id:string,title:string,brief:string,kind:string,directory:string,prefixes:string[],created:string};
export function projectFor(state:any,id?:string):Project{const p=state.projects.find((p:Project)=>p.id===(id||'robot-arm'));if(!p)throw new Error('Unknown project');return p;}
export function belongs(p:Project,path:string){return p.prefixes.some(prefix=>path.startsWith(prefix));}
export function validateGroup(owner:string,stage:string){if(!WORKSTREAMS[owner]?.includes(stage))throw new Error('Invalid workstream or artifact stage');}
export function grouping(path:string,kind:string){if(path.startsWith('runs/'))return {owner:'SIM',stage:kind==='video'||kind==='image'?'Experiment':'Feedback'};if(path.includes('/assets/robots/')||path.startsWith('assets/robots/')||kind==='model')return {owner:'ME',stage:'Detailed CAD'};if(path.includes('scene.xml'))return {owner:'SIM',stage:'Model'};if(path.startsWith('tasks/')||/ENVIRONMENT|LEARNING|PHYSICS|CONTACT|COMPUTE/i.test(path))return {owner:'SIM',stage:'Research'};if(kind==='image')return {owner:'ID',stage:'Concepts'};return {owner:'Brief',stage:'Goals'};}
export async function initializeProjects(root:string,state:any){
 if(!state.projects){state.projects=[{id:'robot-arm',title:'Robot arm assembly',brief:state.brief,kind:'Imported arm · real experiment artifacts',directory:root,prefixes:['assets/robots/','tasks/','runs/','docs/'],created:new Date().toISOString()},{id:'lunar-study',title:'Lunar mass driver',brief:'Explore a lunar mass-driver concept. Define mission goals, compare prior art and architectures, and propose scoped electrical, thermal, mechanical, and trajectory models. This is a concept study, not a validated launcher.',kind:'Concept study · not validated',directory:resolve(root,'apps/desktop/workspaces/lunar-study'),prefixes:['apps/desktop/workspaces/lunar-study/'],created:new Date().toISOString()}];}
 state.workitems??=[];state.artifactMeta??={};
 for(const a of state.agents)a.projectId??='robot-arm';for(const r of state.reviews)r.projectId??='robot-arm';
 const lunar=state.projects.find((p:Project)=>p.id==='lunar-study');if(lunar){await mkdir(lunar.directory,{recursive:true});const f=resolve(lunar.directory,'BRIEF.md');try{await access(f);}catch{await writeFile(f,'# Lunar mass driver — concept study\n\n'+lunar.brief+'\n\n## Open requirements\n\nPayload, destination, throughput, duty cycle, site constraints, power availability, and acceptable acceleration have not been selected.\n\n## Research reference\n\nNASA NTRS: [Applications of a new mass-driver concept](https://ntrs.nasa.gov/citations/19810062908). Its indexed abstract describes operating principles and a lunar-launcher application. The full report has not been reviewed. This reference does not validate a new design.\n\n## Simulation questions\n\n- Which architecture and mission assumptions should be compared?\n- How do electrical power and thermal limits constrain the duty cycle?\n- Which mechanical loads and trajectory constraints need separate models?\n\nNo CAD, numerical simulation, or tested performance is claimed for this project.\n');}}
}
