import {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArmScene} from './ArmScene';
import './style.css';
declare global{interface Window{ASTRA_WORKSPACE:string}}
const token=location.hash.slice(1);
function App(){const [prompt,setPrompt]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const examples=[['Insert a keyed part','Teach the YAM arm to pick up a keyed part, align it with its matching socket, and insert and hold it. Vary the starting positions and key rotation.'],['Sort small parts','Teach the YAM arm to sort small rigid parts into two trays based on shape.'],['Stack two blocks','Teach the YAM arm to pick up a block and place it steadily on another block.']];
 const workspace=(project?:string)=>window.ASTRA_WORKSPACE+'/?'+(project?'project='+encodeURIComponent(project):'view=projects')+'#'+token;
 async function api(path:string,body:any){const r=await fetch('/api/'+path,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not start the project');return d;}
 async function submit(e:React.FormEvent){e.preventDefault();if(!prompt.trim()||busy)return;setBusy(true);setError('');let id:string|undefined;try{const brief=`Robot skill request: ${prompt.trim()}\n\nEmbodiment: existing YAM arm and gripper. First create an inspectable task-specific simulation and measurable success criteria. Training and successful execution must be backed by actual results.`;const project=await api('projects',{title:prompt.trim().split('\n')[0].slice(0,80),brief});id=project.id;await api('agents',{projectId:id,role:'Simulation',prompt:`Build a task-specific simulation proposal for this skill: ${prompt.trim()}\nUse the existing YAM robot assets and reusable task framework as references. Work only in the new project directory. First publish a concise task brief, assumptions, success criteria and an inspectable simulation artifact when tooling permits. Preserve source licenses. Distinguish requested, generated and tested work; do not fabricate training or success. Do not modify existing runs, launch paid GPU work, install packages, contact others or purchase anything. If prerequisites are missing, publish a specific blocker.`});location.href=workspace(id);}catch(e){setError(e instanceof Error?e.message:String(e));setBusy(false);if(id)setError('Project saved, but its engineer could not start. Open the workspace to continue.');}}
 return <div className="skill-page"><header><a className="wordmark" href={'/#'+token}><span className="brand-icon">✳</span> Astra<span className="studio-label">SKILL STUDIO</span></a><a className="workspace-link" href={workspace()}>Open workspace ↗</a></header><div className="hero-art"><div className="art-pill one"/><div className="art-pill two"/><ArmScene token={token}/><span className="robot-caption">YAM / 6-AXIS ARM<span>Illustrative pose · original robot geometry</span></span></div><main><span className="overline">FROM AN IDEA TO A ROBOT SKILL</span><h1>What should your<br/>robot learn?</h1><p className="intro">Describe the task.<br/>Give your robot a world to practice in.</p><form onSubmit={submit}><label className="sr-only" htmlFor="skill">Describe the skill</label><textarea id="skill" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Pick up this part, line it up, and fit it into place…" maxLength={8000} required/><div className="prompt-actions"><span className="robot-preset"><i/>YAM arm + gripper</span><button disabled={busy||!prompt.trim()}>{busy?'Starting engineer…':'Create simulation'} <span>↗</span></button></div></form>{error&&<p className="error" role="alert">{error}</p>}<div className="examples"><span>TRY A SKILL</span>{examples.map(([label,text])=><button key={label} onClick={()=>setPrompt(text)}>{label} ↗</button>)}</div><a className="demo-link" href={workspace('robot-arm')}>Watch a robot learn insertion <span>→</span></a></main><footer><span>DESCRIBE → SIMULATE → LEARN → TEST</span><span>Start in simulation. Build toward the real world.</span></footer></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
