import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {STLLoader} from 'three/examples/jsm/loaders/STLLoader.js';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {vertex,fragment} from './ArmScene';
type Pose={position:number[],quaternion:number[]};type ReplayObject={name:string,body:string,size?:number[],color:number,mesh_path?:string,scale?:number[],local_position?:number[],local_quaternion?:number[],pose?:Pose};type Replay={assembly_path?:string,label?:string,robot_instances?:{id:string,urdf_path?:string,body_prefix?:string,body_map?:Record<string,string>}[],default_time?:number,camera?:{target:number[],position:number[]},frames:{time:number,phase?:string,machine_command?:string,vise_gap_m?:number,bodies:Record<string,Pose>}[],objects:ReplayObject[]};
export function ReplayScene({url,token}:{url:string,token:string}){
 const fileUrl=(p:string)=>{const project=p.startsWith('assets/robots/')?'robot-arm':new URL(url,location.href).searchParams.get('projectId')||'robot-arm';return (p.startsWith('assets/workcells/')?'/studio-api/asset?path=':'/api/artifact?projectId='+encodeURIComponent(project)+'&path=')+encodeURIComponent(p)+'&token='+token;};
 const host=useRef<HTMLDivElement>(null),clock=useRef(0),play=useRef(false),reset=useRef(()=>{}),speed=useRef(1),inspect=useRef(false),focusPart=useRef((name:string)=>{});const [rate,setRate]=useState(1),[partsOpen,setPartsOpen]=useState(false),[exploded,setExploded]=useState(false),[part,setPart]=useState('');const [data,setData]=useState<Replay|null>(null),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[error,setError]=useState(''),[frameInfo,setFrameInfo]=useState<Replay['frames'][0]|null>(null);
 useEffect(()=>{let dead=false;setData(null);setError('');inspect.current=false;setExploded(false);setPart('');clock.current=0;setTime(0);play.current=false;setPlaying(false);fetch(url).then(r=>{if(!r.ok)throw Error('Replay unavailable');return r.json();}).then(d=>{if(!d.frames?.length)throw Error('Empty recording');if(!dead){clock.current=d.default_time??d.frames[0].time;setTime(clock.current);setData(d);}}).catch(e=>{if(!dead)setError(e.message);});return()=>{dead=true;};},[url]);
 useEffect(()=>{if(!data||!host.current)return;let dead=false;const scene=new T.Scene();scene.background=new T.Color('#eceee7');const camera=new T.PerspectiveCamera(35,1,.005,30);camera.up.set(0,0,1);const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.current.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.15;controls.maxDistance=4;controls.maxPolarAngle=Math.PI*.92;
 const partMeshes=new Map<string,{mesh:T.Mesh,base:T.Vector3,offset:T.Vector3,color:number}>();const bodies=new Map<string,T.Group>(),geometries:T.BufferGeometry[]=[],materials:T.Material[]=[];const vec=(v:string|null|undefined)=>new T.Vector3(...(v||'0 0 0').split(/\s+/).map(Number) as [number,number,number]);
 const ink=(color:number)=>{const m=new T.ShaderMaterial({vertexShader:vertex,fragmentShader:fragment,uniforms:{ink:{value:new T.Color(color)}}});materials.push(m);return m;};const outline=new T.ShaderMaterial({side:T.BackSide,vertexShader:'void main(){gl_Position=projectionMatrix*modelViewMatrix*vec4(position+normal*.0007,1.);}',fragmentShader:'void main(){gl_FragColor=vec4(.035,.08,.08,1.);}'});materials.push(outline);const material=[ink(0xe8e6df),ink(0x518f91),ink(0x173b3b)];
 function addMesh(g:T.Group,geo:T.BufferGeometry,m:T.Material){geometries.push(geo);const mesh=new T.Mesh(geo,m);mesh.add(new T.Mesh(geo,outline));g.add(mesh);return mesh;}
 function pose(frame:Replay['frames'][0]){for(const [name,g]of bodies){const p=frame.bodies[name];if(p){g.position.fromArray(p.position);g.quaternion.fromArray(p.quaternion);}}}
 const home=()=>{controls.target.fromArray(data.camera?.target||[.23,0,.22]);camera.position.fromArray(data.camera?.position||[1.03,-1.1,.78]);controls.update();};reset.current=home;home();
 const floor=new T.Mesh(new T.PlaneGeometry(4,4),new T.MeshBasicMaterial({color:0xe0e5da}));floor.position.z=-.004;scene.add(floor);geometries.push(floor.geometry);materials.push(floor.material);const grid=new T.GridHelper(2,40,0xbac9b8,0xd1dacc);grid.rotation.x=Math.PI/2;grid.position.z=-.003;scene.add(grid);
 const asset=fileUrl;
 async function load(){const loader=new STLLoader(),jobs:Promise<void>[]=[];for(const instance of data!.robot_instances||[{id:'yam',body_prefix:''}]){const path=instance.urdf_path||'assets/robots/yam/v1/yam.urdf',r=await fetch(asset(path));if(!r.ok)throw Error('Robot model unavailable');const xml=new DOMParser().parseFromString(await r.text(),'application/xml');
 for(const l of xml.querySelectorAll('robot > link')){const linkName=l.getAttribute('name')!,name=instance.body_map?.[linkName]??((instance.body_prefix||'')+linkName);if(!data!.frames[0].bodies[name])continue;const g=new T.Group();bodies.set(name,g);scene.add(g);for(const v of l.querySelectorAll(':scope > visual')){const mesh=v.querySelector('mesh');if(!mesh)continue;jobs.push((async()=>{const p=new URL(mesh.getAttribute('filename')!,'http://local/'+path).pathname.slice(1),r=await fetch(asset(p));if(!r.ok)throw Error('Robot mesh unavailable');const geo=loader.parse(await r.arrayBuffer());if(dead){geo.dispose();return;}const m=addMesh(g,geo,material[/tip_/.test(name)?2:/link1|link4|link5/.test(name)?1:0]);const o=v.querySelector('origin');m.position.copy(vec(o?.getAttribute('xyz')));const rpy=vec(o?.getAttribute('rpy'));m.rotation.set(rpy.x,rpy.y,rpy.z,'ZYX');m.scale.copy(vec(mesh.getAttribute('scale')||'1 1 1'));})());}}
 }
 for(const o of data!.objects||[]){let g=bodies.get(o.body);if(!g){g=new T.Group();bodies.set(o.body,g);scene.add(g);if(o.pose){g.position.fromArray(o.pose.position);g.quaternion.fromArray(o.pose.quaternion);}}const group=g;const attach=(geo:T.BufferGeometry)=>{if(dead){geo.dispose();return;}const mesh=addMesh(group,geo,ink(o.color));if(o.scale)mesh.scale.fromArray(o.scale);if(o.local_position)mesh.position.fromArray(o.local_position);if(o.local_quaternion)mesh.quaternion.fromArray(o.local_quaternion);geo.computeBoundingBox();const offset=geo.boundingBox!.getCenter(new T.Vector3()).multiply(mesh.scale);if(offset.length()<.001)offset.set(.01,.01,.01);offset.normalize().multiplyScalar(.035);partMeshes.set(o.name,{mesh,base:mesh.position.clone(),offset,color:o.color});};if(o.mesh_path){jobs.push((async()=>{const r=await fetch(asset(o.mesh_path!));if(!r.ok)throw Error('Fixture mesh unavailable: '+o.name);attach(loader.parse(await r.arrayBuffer()));})());}else if(o.size){attach(new T.BoxGeometry(...o.size as [number,number,number]));}}await Promise.all(jobs);if(!dead)pose(data!.frames[0]);}
 focusPart.current=(name:string)=>{for(const [n,p] of partMeshes){(p.mesh.material as T.ShaderMaterial).uniforms.ink.value.set(n===name?0xe2ae5e:p.color);}const found=partMeshes.get(name);if(found){const b=new T.Box3().setFromObject(found.mesh),c=b.getCenter(new T.Vector3());controls.target.copy(c);controls.update();}};
 load().catch(e=>{if(!dead)setError(e.message);});let prev=performance.now(),ui=0;const end=data.frames.at(-1)!.time;
 const ro=new ResizeObserver(()=>{if(!host.current)return;const w=host.current.clientWidth,h=host.current.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();});ro.observe(host.current);
 renderer.setAnimationLoop(now=>{const dt=Math.min((now-prev)/1000,.1);prev=now;if(play.current){clock.current=Math.min(end,clock.current+dt*speed.current);if(clock.current>=end){play.current=false;setPlaying(false);}}let lo=0,hi=data.frames.length-1;while(lo<hi){const mid=Math.ceil((lo+hi)/2);if(data.frames[mid].time<=clock.current)lo=mid;else hi=mid-1;}pose(data.frames[lo]);for(const [name,p] of partMeshes){p.mesh.position.copy(p.base);if(inspect.current&&/vise|screw|jaw|handle|crank|actuator|slider|bearing|rail|seat/.test(name))p.mesh.position.add(p.offset);}controls.update();renderer.render(scene,camera);if(now-ui>80){setTime(clock.current);setFrameInfo(data.frames[lo]);ui=now;}});
 return()=>{dead=true;ro.disconnect();renderer.setAnimationLoop(null);controls.dispose();geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());grid.geometry.dispose();(grid.material as T.Material).dispose();renderer.dispose();renderer.domElement.remove();};
 },[data,token]);
 const end=data?.frames.at(-1)?.time||0,staticView=data?.frames.length===1||data?.label==='static_design';return <div className="replay-shell"><div ref={host} className="replay-canvas"/>{(!data||error)&&<div className="replay-loading">{error||'Loading recorded simulation…'}</div>}<span className="replay-hint">Drag to orbit · Scroll to zoom · Right-drag to pan</span><div className="replay-command">{frameInfo?.phase&&<span>{frameInfo.phase.replaceAll("_"," ")}</span>}{frameInfo?.machine_command&&<strong>Fixture command: {frameInfo.machine_command}</strong>}{frameInfo?.vise_gap_m!==undefined&&<small>Jaw gap {(frameInfo.vise_gap_m*1000).toFixed(1)} mm · scripted powered fixture</small>}</div><div className="replay-toolbar">{!!data?.objects?.length&&<button onClick={()=>setPartsOpen(!partsOpen)}>CAD parts ({data.objects.length})</button>}{!!data?.objects?.some(o=>o.mesh_path)&&<button onClick={()=>{inspect.current=!inspect.current;setExploded(inspect.current);play.current=false;setPlaying(false);}}>{exploded?"Restore assembly":"Exploded view"}</button>}</div>{partsOpen&&<div className="replay-parts">{data?.assembly_path&&<a href={fileUrl(data.assembly_path)} target="_blank" rel="noopener noreferrer">Download assembly STEP ↗</a>}{data?.objects.map(o=><div key={o.name}><button className={part===o.name?"selected":""} onClick={()=>{setPart(o.name);focusPart.current(o.name);}}>{o.name.replaceAll("_"," ")}</button>{o.mesh_path&&<a href={fileUrl(o.mesh_path)} target="_blank" rel="noopener noreferrer" aria-label={"Download "+o.name}>↗</a>}</div>)}</div>}{exploded&&<div className="exploded-label">Exploded inspection · not a simulated pose</div>}<div className="replay-controls">{staticView?<span>Static design preview · not a trained execution</span>:<><button disabled={!data||exploded} onClick={()=>{if(clock.current>=end)clock.current=data?.frames[0].time||0;play.current=!play.current;setPlaying(play.current);}}>{playing?'Pause':'▶ Play'}</button><select aria-label="Playback speed" value={rate} onChange={e=>{const r=Number(e.target.value);speed.current=r;setRate(r);}}>{[.5,1,2,4].map(r=><option key={r} value={r}>{r}× playback</option>)}</select><input disabled={exploded} aria-label="Replay time" type="range" min={data?.frames[0].time||0} max={end} step={.02} value={time} onChange={e=>{clock.current=Number(e.target.value);setTime(clock.current);}}/><span>{time.toFixed(1)} / {end.toFixed(1)} s</span></>}<button onClick={()=>reset.current()}>Reset view</button></div></div>;
}
