import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {STLLoader} from 'three/examples/jsm/loaders/STLLoader.js';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {vertex,fragment} from './ArmScene';
type Pose={position:number[],quaternion:number[]};type Replay={frames:{time:number,bodies:Record<string,Pose>}[],objects:{name:string,body:string,size:number[],color:number}[]};
export function ReplayScene({url,token}:{url:string,token:string}){
 const host=useRef<HTMLDivElement>(null),clock=useRef(0),play=useRef(false),reset=useRef(()=>{});const [data,setData]=useState<Replay|null>(null),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let dead=false;setData(null);setError('');clock.current=0;setTime(0);play.current=false;setPlaying(false);fetch(url).then(r=>{if(!r.ok)throw Error('Replay unavailable');return r.json();}).then(d=>{if(!d.frames?.length)throw Error('Empty recording');if(!dead)setData(d);}).catch(e=>{if(!dead)setError(e.message);});return()=>{dead=true;};},[url]);
 useEffect(()=>{if(!data||!host.current)return;let dead=false;const scene=new T.Scene();scene.background=new T.Color('#eceee7');const camera=new T.PerspectiveCamera(35,1,.005,30);camera.up.set(0,0,1);const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.current.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.15;controls.maxDistance=4;controls.maxPolarAngle=Math.PI*.92;
 const bodies=new Map<string,T.Group>(),geometries:T.BufferGeometry[]=[],materials:T.Material[]=[];const vec=(v:string|null|undefined)=>new T.Vector3(...(v||'0 0 0').split(/\s+/).map(Number) as [number,number,number]);
 const ink=(color:number)=>{const m=new T.ShaderMaterial({vertexShader:vertex,fragmentShader:fragment,uniforms:{ink:{value:new T.Color(color)}}});materials.push(m);return m;};const outline=new T.ShaderMaterial({side:T.BackSide,vertexShader:'void main(){gl_Position=projectionMatrix*modelViewMatrix*vec4(position+normal*.0007,1.);}',fragmentShader:'void main(){gl_FragColor=vec4(.035,.08,.08,1.);}'});materials.push(outline);const material=[ink(0xe8e6df),ink(0x518f91),ink(0x173b3b)];
 function addMesh(g:T.Group,geo:T.BufferGeometry,m:T.Material){geometries.push(geo);const mesh=new T.Mesh(geo,m);mesh.add(new T.Mesh(geo,outline));g.add(mesh);return mesh;}
 function pose(frame:Replay['frames'][0]){for(const [name,g]of bodies){const p=frame.bodies[name];if(p){g.position.fromArray(p.position);g.quaternion.fromArray(p.quaternion);}}}
 const home=()=>{controls.target.set(.23,0,.22);camera.position.set(1.03,-1.1,.78);controls.update();};reset.current=home;home();
 const floor=new T.Mesh(new T.PlaneGeometry(4,4),new T.MeshBasicMaterial({color:0xe0e5da}));floor.position.z=-.004;scene.add(floor);geometries.push(floor.geometry);materials.push(floor.material);const grid=new T.GridHelper(2,40,0xbac9b8,0xd1dacc);grid.rotation.x=Math.PI/2;grid.position.z=-.003;scene.add(grid);
 const asset=(p:string)=>'/api/artifact?projectId=robot-arm&path='+encodeURIComponent(p)+'&token='+token;
 async function load(){const path='assets/robots/yam/v1/yam.urdf',r=await fetch(asset(path));if(!r.ok)throw Error('Robot model unavailable');const xml=new DOMParser().parseFromString(await r.text(),'application/xml'),loader=new STLLoader();const jobs:Promise<void>[]=[];
 for(const l of xml.querySelectorAll('robot > link')){const name=l.getAttribute('name')!;if(!data!.frames[0].bodies[name])continue;const g=new T.Group();bodies.set(name,g);scene.add(g);for(const v of l.querySelectorAll(':scope > visual')){const mesh=v.querySelector('mesh');if(!mesh)continue;jobs.push((async()=>{const p=new URL(mesh.getAttribute('filename')!,'http://local/'+path).pathname.slice(1),r=await fetch(asset(p));if(!r.ok)throw Error('Robot mesh unavailable');const geo=loader.parse(await r.arrayBuffer());if(dead){geo.dispose();return;}const m=addMesh(g,geo,material[/tip_/.test(name)?2:/link1|link4|link5/.test(name)?1:0]);const o=v.querySelector('origin');m.position.copy(vec(o?.getAttribute('xyz')));const rpy=vec(o?.getAttribute('rpy'));m.rotation.set(rpy.x,rpy.y,rpy.z,'ZYX');m.scale.copy(vec(mesh.getAttribute('scale')||'1 1 1'));})());}}
 for(const o of data!.objects||[]){const g=new T.Group();bodies.set(o.body,g);scene.add(g);addMesh(g,new T.BoxGeometry(...o.size as [number,number,number]),ink(o.color));}await Promise.all(jobs);if(!dead)pose(data!.frames[0]);}
 load().catch(e=>{if(!dead)setError(e.message);});let prev=performance.now(),ui=0;const end=data.frames.at(-1)!.time;
 const ro=new ResizeObserver(()=>{if(!host.current)return;const w=host.current.clientWidth,h=host.current.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();});ro.observe(host.current);
 renderer.setAnimationLoop(now=>{const dt=Math.min((now-prev)/1000,.1);prev=now;if(play.current){clock.current=Math.min(end,clock.current+dt);if(clock.current>=end){play.current=false;setPlaying(false);}}let lo=0,hi=data.frames.length-1;while(lo<hi){const mid=Math.ceil((lo+hi)/2);if(data.frames[mid].time<=clock.current)lo=mid;else hi=mid-1;}pose(data.frames[lo]);controls.update();renderer.render(scene,camera);if(now-ui>80){setTime(clock.current);ui=now;}});
 return()=>{dead=true;ro.disconnect();renderer.setAnimationLoop(null);controls.dispose();geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());grid.geometry.dispose();(grid.material as T.Material).dispose();renderer.dispose();renderer.domElement.remove();};
 },[data,token]);
 const end=data?.frames.at(-1)?.time||0;return <div className="replay-shell"><div ref={host} className="replay-canvas"/>{(!data||error)&&<div className="replay-loading">{error||'Loading recorded simulation…'}</div>}<span className="replay-hint">Drag to orbit · Scroll to zoom · Right-drag to pan</span><div className="replay-controls"><button disabled={!data} onClick={()=>{if(clock.current>=end)clock.current=0;play.current=!play.current;setPlaying(play.current);}}>{playing?'Pause':'▶ Play'}</button><input aria-label="Replay time" type="range" min={0} max={end} step={.02} value={time} onChange={e=>{clock.current=Number(e.target.value);setTime(clock.current);}}/><span>{time.toFixed(1)} / {end.toFixed(1)} s</span><button onClick={()=>reset.current()}>Reset view</button></div></div>;
}
