import {useEffect,useState} from 'react';
import {ReplayScene} from './ReplayScene';
type Stage={id:string,title:string,status:string,kind:string,path?:string,description?:string,provenance?:string};
export function StageWorkspace({manifest,asset}:{manifest:any,asset:(path:string)=>string}){
 const stages:Stage[]=manifest.stages||[],[selected,setSelected]=useState(manifest.default_stage||stages[0]?.id);
 useEffect(()=>{setSelected(manifest.default_stage||stages[0]?.id);},[manifest.template_id]);
 const [report,setReport]=useState<any>(null);
 const stage=stages.find(s=>s.id===selected)||stages[0];useEffect(()=>{let stop=false;setReport(null);if(stage?.kind==='artifact'&&stage.path?.endsWith('configuration-report.json'))fetch(asset(stage.path)).then(r=>r.ok?r.json():null).then(d=>{if(!stop)setReport(d);}).catch(()=>{});return()=>{stop=true;};},[stage?.path]);if(!stage)return null;
 return <div className="stage-workspace"><nav className="stage-rail" aria-label="Product stages">{stages.map((s,i)=><button key={s.id} className={s.id===stage.id?'selected':''} onClick={()=>setSelected(s.id)}><span>{i+1}</span><strong>{s.title}</strong><small>{s.status==='running'?'Working':s.status==='pending'?'Not started':s.status==='blocked'?'Needs work':s.provenance==='prepared'?'Prepared':s.provenance==='recorded'?'Recorded':s.status==='complete'?'Complete':s.status}</small></button>)}</nav><div className="stage-context"><h2>{stage.title}</h2><span>{stage.provenance==='prepared'?'Prepared example':stage.provenance==='recorded'?'Recorded evidence':stage.provenance==='live'?'Current run':''}</span></div><p className="stage-description">{stage.description}</p>{stage.path&&stage.kind==='image'?<div className="stage-image"><img src={asset(stage.path)} alt={stage.title}/></div>:stage.path&&stage.kind==='replay'?<div className="skill-sim-view"><ReplayScene url={asset(stage.path)} token={location.hash.slice(1)}/></div>:stage.kind==='results'?<><div className="result-grid">{manifest.metrics?.map((m:any)=><div key={m.id||m.label}><strong>{m.value}</strong><h3>{m.label}</h3><p>{m.detail}</p></div>)}</div><ul className="result-limits">{manifest.limitations?.map((l:string)=><li key={l}>{l}</li>)}</ul></>:<div className="stage-pending">{report?.validation&&<div className="configuration-checks"><span>{report.validation.mujoco_load?"✓ Scene compiled":"Scene not compiled"}</span><span>{report.validation.gym_reset_step_tested?"✓ Gym reset and step checked":"Gym task still needs implementation"}</span><span>No new training performed</span></div>}<strong>{stage.status==='pending'?'This stage has not run yet':stage.status==='running'?'The engineer is working on this stage':stage.status==='blocked'?'This stage needs more work':'Inspect the saved setup'}</strong>{stage.path&&<a href={asset(stage.path)} target="_blank" rel="noopener noreferrer">Open artifact ↗</a>}</div>}</div>;
}
