import {useEffect,useState,useRef} from 'react';
export function LearningDemo({assetURL,onEngineering}:{assetURL:(path:string)=>string,onEngineering:()=>void}){
 const player=useRef<HTMLVideoElement>(null),[playing,setPlaying]=useState(false);
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[clip,setClip]=useState('success');
 useEffect(()=>{let cancelled=false;fetch(assetURL('runs/hackathon-demo/final-demo.json')).then(r=>{if(!r.ok)throw new Error('Demo evidence unavailable');return r.json();}).then(d=>{if(!cancelled)setData(d);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[]);
 if(!data)return <main className="learning-demo"><h1>{error||'Loading experiment evidence…'}</h1><button onClick={onEngineering}>Open engineering workspace →</button></main>;
 const video=data.videos.find((v:any)=>v.id===clip)||data.videos[0];
 return <main className="learning-demo"><div className="learning-title"><div><span className="eyebrow">ROBOT LEARNING · PREPARED EXPERIMENT</span><h1>A robot learns the missing skill.</h1><p>Pick up a custom part. Align its key. Insert and hold.</p></div><button className="detail-link" onClick={onEngineering}>Engineering workspace ↗</button></div>
 <div className="learning-scope">Simulation-state observations · Learned specialists + conventional control · No hardware validation</div>
 <div className="learning-layout"><section><nav className="visual-tabs" aria-label="Experiment recordings">{data.videos.map((v:any)=><button key={v.id} className={clip===v.id?'selected':''} onClick={()=>{setClip(v.id);setPlaying(false);}}>{v.id==='failure'?'Earlier failure':v.id==='success'?'Final execution':'New layouts'}</button>)}</nav><div className="learning-video"><video ref={player} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} key={video.path} src={assetURL(video.path)} controls playsInline preload="metadata"/>{!playing&&<button className="learning-play" onClick={()=>player.current?.play().catch(()=>{})}>▶ Play recording</button>}</div><div className="learning-caption"><strong>{video.title}</strong><p>{video.caption}</p><small>{video.kind} · Prepared evidence</small></div></section>
 <aside className="learning-results"><span className="eyebrow">MEASURED RESULTS</span>{data.metrics.filter((m:any)=>m.id!=='training').map((m:any)=><div className="learning-metric" key={m.id}><strong>{m.value}</strong><h3>{m.label}</h3><p>{m.detail}</p></div>)}<div className="learning-skills"><span className="eyebrow">COMPOSED SKILLS</span><p>{data.skills.map((s:any)=>s.name).join(' → ')}</p><small>{data.total_learned_parameters.toLocaleString()} learned parameters + scripted targets, guards and IK</small></div></aside></div>
 {data.fallback_reel&&<a className="detail-link" href={assetURL(data.fallback_reel.path)} target="_blank" rel="noopener noreferrer">Watch the full demo reel ↗</a>}<details className="learning-evidence"><summary>How it learned &amp; what this proves</summary><ol>{data.learning_story.map((text:string)=><li key={text}>{text}</li>)}</ol><p><strong>{data.metrics.find((m:any)=>m.id==='training')?.value} pickup-model training.</strong> {data.metrics.find((m:any)=>m.id==='training')?.detail}</p><ul>{data.limitations.map((text:string)=><li key={text}>{text}</li>)}</ul><p>{data.visual_status.label}: RGB {data.visual_status.rgb_successes}/{data.visual_status.episodes_per_condition}; blank RGB {data.visual_status.blank_rgb_successes}/{data.visual_status.episodes_per_condition}.</p><div className="learning-sources">{data.sources.map((s:any)=><a key={s.id} href={assetURL(s.path)} target="_blank" rel="noopener noreferrer">{s.id.replaceAll('_',' ')} report ↗</a>)}</div></details></main>;
}
