import {resolve} from 'node:path';
import {mkdir,rename} from 'node:fs/promises';
export type Skill={id:string,title:string,description:string,status:string,phase:string,project_id?:string,agent_id?:string,created_at?:string,updated_at?:string,manifest_path?:string,preview_path?:string,message?:string,metrics?:any[],artifacts?:any[]};
export async function readJson(path:string,fallback:any){try{return await Bun.file(path).json();}catch{return fallback;}}
export async function listSkills(here:string){
 const root=resolve(here,'../..'),saved=await readJson(resolve(here,'.local/skills.json'),[]),registry=await readJson(resolve(root,'runs/skill-studio/skills.json'),{skills:[]}),demo=await readJson(resolve(root,'runs/hackathon-demo/final-demo.json'),null);
 const defaults:Skill[]=demo?[{id:'keyed-insertion',title:'Pick, align & insert',description:'A composed skill for inserting a custom keyed part.',status:'complete',phase:'Evaluated in simulation',project_id:'robot-arm',manifest_path:'runs/hackathon-demo/final-demo.json',preview_path:demo.videos?.find((v:any)=>v.id==='success')?.path,metrics:demo.metrics?.filter((m:any)=>['nominal','stress'].includes(m.id))},{id:'visual-candidate',title:'Learn from camera images',description:'An experimental visual student. No visual benefit demonstrated.',status:'failed',phase:'Not promoted',project_id:'robot-arm',message:demo.visual_status?.label,metrics:[{label:'RGB evaluation',value:`${demo.visual_status?.rgb_successes}/5`},{label:'Blank-image control',value:`${demo.visual_status?.blank_rgb_successes}/5`}],artifacts:[{label:'Visual evaluation',path:'runs/hackathon-demo/evidence/visual.json'}]}]:[];
 return [...new Map([...defaults,...saved,...(registry.skills||[])].map((s:Skill)=>[s.id,s])).values()];
}
let write=Promise.resolve();
export function saveSkill(here:string,input:any){return write=write.catch(()=>{}).then(async()=>{if(typeof input.id!=='string'||typeof input.title!=='string'||!input.id||!input.title||input.title.length>200)throw new Error('Invalid skill');const dir=resolve(here,'.local');await mkdir(dir,{recursive:true});const path=resolve(dir,'skills.json'),rows=await readJson(path,[]);const s:Skill={id:input.id,title:input.title,description:String(input.description||'').slice(0,8000),project_id:input.project_id,agent_id:input.agent_id,status:'planning',phase:'Defining the task',created_at:rows.find((r:Skill)=>r.id===input.id)?.created_at||new Date().toISOString(),updated_at:new Date().toISOString()};const next=rows.filter((r:Skill)=>r.id!==s.id);next.push(s);await Bun.write(path+'.tmp',JSON.stringify(next,null,2));await rename(path+'.tmp',path);return s;}) as any;}
