import {resolve} from 'node:path';
import {mkdir,rename} from 'node:fs/promises';
export type Skill={id:string,title:string,description:string,status:string,phase:string,project_id?:string,agent_id?:string,created_at?:string,updated_at?:string,manifest_path?:string,preview_path?:string,message?:string,metrics?:any[],artifacts?:any[]};
export async function readJson(path:string,fallback:any){try{return await Bun.file(path).json();}catch{return fallback;}}
export async function listSkills(here:string){
 const deleted=await readJson(resolve(here,'.local/deleted-skills.json'),[]);
 const archived=await readJson(resolve(here,'.local/archived-skills.json'),[]);
 const root=resolve(here,'../..'),saved=await readJson(resolve(here,'.local/skills.json'),[]),registry=await readJson(resolve(root,'runs/skill-studio/skills.json'),{skills:[]}),demo=await readJson(resolve(root,'runs/hackathon-demo/final-demo.json'),null);
 for(const s of saved){if(typeof s.project_id!=='string'||!/^[a-zA-Z0-9_-]+$/.test(s.project_id))continue;const progress=await readJson(resolve(root,'apps/desktop/workspaces',s.project_id,'SKILL.json'),null);if(progress){for(const key of ['status','phase','message','preview_path','preview_label','manifest_path','metrics','artifacts'])if(progress[key]!==undefined)s[key]=progress[key];s.progress_artifact=true;}}
 const defaults:Skill[]=demo?[{id:'keyed-insertion',title:'Pick, align & insert',description:'A composed skill for inserting a custom keyed part.',status:'complete',phase:'Evaluated in simulation',project_id:'robot-arm',manifest_path:'runs/hackathon-demo/final-demo.json',preview_path:demo.videos?.find((v:any)=>v.id==='success')?.path,metrics:demo.metrics?.filter((m:any)=>['nominal','stress'].includes(m.id))},{id:'visual-candidate',title:'Learn from camera images',description:'An experimental visual student. No visual benefit demonstrated.',status:'failed',phase:'Not promoted',project_id:'robot-arm',message:demo.visual_status?.label,metrics:[{label:'RGB evaluation',value:`${demo.visual_status?.rgb_successes}/5`},{label:'Blank-image control',value:`${demo.visual_status?.blank_rgb_successes}/5`}],artifacts:[{label:'Visual evaluation',path:'runs/hackathon-demo/evidence/visual.json'}]}]:[];
 return [...new Map([...defaults,...saved,...(registry.skills||[])].map((s:Skill)=>[s.id,s])).values()].filter(s=>!deleted.includes(s.id)).map(s=>({...s,archived:archived.includes(s.id)}));
}
let write:Promise<any>=Promise.resolve();
export function saveSkill(here:string,input:any){return write=write.catch(()=>{}).then(async()=>{if(typeof input.id!=='string'||typeof input.title!=='string'||!input.id||!input.title||input.title.length>200)throw new Error('Invalid skill');const dir=resolve(here,'.local');await mkdir(dir,{recursive:true});const path=resolve(dir,'skills.json'),rows=await readJson(path,[]);const s:Skill={id:input.id,title:input.title,description:String(input.description||'').slice(0,8000),project_id:input.project_id,agent_id:input.agent_id,status:'planning',phase:'Defining the task',created_at:rows.find((r:Skill)=>r.id===input.id)?.created_at||new Date().toISOString(),updated_at:new Date().toISOString()};const next=rows.filter((r:Skill)=>r.id!==s.id);next.push(s);await Bun.write(path+'.tmp',JSON.stringify(next,null,2));await rename(path+'.tmp',path);return s;}) as any;}

export async function archiveSkills(here:string,ids:string[],archived=true){if(!Array.isArray(ids)||ids.some(id=>typeof id!=='string'))throw new Error('Invalid skill IDs');const dir=resolve(here,'.local');await mkdir(dir,{recursive:true});const path=resolve(dir,'archived-skills.json'),prior=await readJson(path,[]);const result=archived?[...new Set([...prior,...ids])]:prior.filter((id:string)=>!ids.includes(id));await Bun.write(path+'.tmp',JSON.stringify(result,null,2));await rename(path+'.tmp',path);return result;}

export function deleteSkill(here:string,id:string){return write=write.catch(()=>{}).then(async()=>{if(typeof id!=='string'||!id)throw new Error('Invalid skill');const dir=resolve(here,'.local');await mkdir(dir,{recursive:true});const path=resolve(dir,'deleted-skills.json');const ids=await readJson(path,[]);await Bun.write(path+'.tmp',JSON.stringify([...new Set([...ids,id])],null,2));await rename(path+'.tmp',path);return {removed:true,preserved:'Experiment files and agent sessions are retained'};});}
