import {liveLearning} from './live-learning';
import {resolve} from 'node:path';
import {mkdir,rename,readdir} from 'node:fs/promises';
import {readJson} from './catalog';
const ids=['keyed-insertion','machine-tending','manual-vise'];
export async function configuredSkills(here:string){const dir=resolve(here,'.local/configurations');try{return await Promise.all((await readdir(dir)).filter(n=>n.endsWith('.json')).map(n=>readJson(resolve(dir,n),null))).then(async rows=>{const deleted=await readJson(resolve(here,'.local/deleted-skills.json'),[]),archived=await readJson(resolve(here,'.local/archived-skills.json'),[]);return rows.filter(r=>r&&!deleted.includes(r.id)).map(r=>({...r,archived:archived.includes(r.id)}));});}catch{return [];}}
export async function configure(here:string,scenario:string){
 if(!ids.includes(scenario))throw Error('Unknown prepared scenario');const root=resolve(here,'../..'),catalog=await readJson(resolve(root,'assets/workcells/demo-workflows/catalog.json'),{scenarios:[]}),entry=catalog.scenarios?.find((s:any)=>s.id===scenario);if(!entry?.manifest_path)throw Error('Prepared scenario not available yet');
 const source=await readJson(resolve(root,entry.manifest_path),null);if(!source)throw Error('Scenario manifest unavailable');const runner=resolve(root,'tools/configure_demo_environment.py');if(!await Bun.file(runner).exists())throw Error('Configuration runner not available yet');
 const id=crypto.randomUUID(),output='runs/demo-configurations/'+id,dir=resolve(root,output),records=resolve(here,'.local/configurations');await mkdir(dir,{recursive:true});await mkdir(records,{recursive:true});const recordPath=resolve(records,id+'.json');
 let row:any={id,title:entry.title||source.title||scenario,description:entry.prompt||source.prompt||'Configure a prepared practice world.',status:'building',phase:'Configuring environment',project_id:'robot-arm',manifest_path:output+'/demo.json',message:'Preparing an environment from an existing template. No new training has run.',updated_at:new Date().toISOString()};
 const manifest={...source,metrics:scenario==='keyed-insertion'?[]:source.metrics,videos:scenario==='keyed-insertion'?[]:source.videos,template_id:scenario,default_stage:'gym',stages:(source.stages||[]).map((s:any)=>s.id==='gym'?{...s,status:'running',provenance:'live',description:'Configuring this practice world from a prepared template.'}:scenario==='keyed-insertion'&&s.id==='learn'?{...s,status:'pending',provenance:'live',path:undefined,description:'A fresh small model will be trained and evaluated in this run. No results yet.'}:s)};
 const save=async()=>{await Bun.write(recordPath+'.tmp',JSON.stringify(row));await rename(recordPath+'.tmp',recordPath);};await Bun.write(resolve(dir,'demo.json'),JSON.stringify(manifest));await save();
 const proc=Bun.spawn(['/tmp/clonebench-cad-env/bin/python',runner,'--scenario',scenario,'--output',output+'/environment'],{cwd:root,env:{...process.env,PYTHONPATH:resolve(root,'src')+':'+resolve(root,'tools'),PYTHONUNBUFFERED:'1'},stdout:'pipe',stderr:'pipe'});
 void (async()=>{const stderr=new Response(proc.stderr).text();let buffer='';const reader=proc.stdout.getReader(),decoder=new TextDecoder();try{while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i);buffer=buffer.slice(i+1);try{const event=JSON.parse(line);if(event.event==='stage'){row={...row,phase:({resolve_template:'Choose template',bundle_assets:'Prepare CAD assets',compile_model:'Compile simulation',write_report:'Save configuration'} as any)[event.stage]||'Configure environment',message:event.message||row.message};await save();}}catch{}}}
 const exit=await proc.exited;await Bun.write(resolve(dir,'configuration-stderr.log'),await stderr);const ok=exit===0;row={...row,status:ok?(scenario==='manual-vise'?'design':'review'):'blocked',phase:ok?'Environment configured':'Configuration needs attention',message:ok?(scenario==='manual-vise'?'Design scene configured. Contact task implementation and training remain pending.':'Prepared environment configured in this run. Learning results shown are earlier recorded evidence; no new training has run.'):'Configuration did not complete. Inspect the saved log.'};
 manifest.stages=manifest.stages.map((s:any)=>s.id==='gym'?{...s,status:ok?'complete':'blocked',kind:'artifact',path:output+'/environment/configuration-report.json',description:row.message}:s);await Bun.write(resolve(dir,'demo.json'),JSON.stringify(manifest));await save();
 if(ok&&scenario==='keyed-insertion'){
  row={...row,status:'training',phase:'Training a fresh skill',message:'Fresh behavioral cloning from prepared demonstrations; downstream controllers stay frozen.'};manifest.default_stage='learn';manifest.stages=manifest.stages.map((s:any)=>s.id==='learn'?{...s,status:'running',provenance:'live',description:row.message}:s);await Bun.write(resolve(dir,'demo.json'),JSON.stringify(manifest));await save();
  const {report,demo}=await liveLearning(root,output,async(stage,message)=>{const evaluating=/eval|baseline|replay|test/.test(stage);row={...row,status:evaluating?'evaluating':'training',phase:evaluating?'Evaluating the new skill':'Training a fresh skill',message};manifest.stages=manifest.stages.map((s:any)=>s.id==='learn'?{...s,status:'running',description:message}:s);await Bun.write(resolve(dir,'demo.json'),JSON.stringify(manifest));await save();});
  for(const key of ['videos','metrics','limitations','scope_label','sources'])if(demo[key]!==undefined)manifest[key]=demo[key];
  const accepted=report.accepted;row={...row,status:accepted?'complete':'failed',phase:accepted?'New skill evaluated':'Candidate not promoted',message:accepted?'Fresh training and paired evaluation completed. Inspect this run’s evidence.':'Fresh evaluation did not meet the promotion criterion. Inspect the measured outcomes.',metrics:demo.metrics};
  manifest.stages=manifest.stages.map((s:any)=>s.id==='learn'?{...s,status:accepted?'complete':'blocked',kind:'results',provenance:'live',path:output+'/learning/report.json',description:row.message}:s);await Bun.write(resolve(dir,'demo.json'),JSON.stringify(manifest));await save();
 }
 }catch(e){row={...row,status:'blocked',phase:'Configuration interrupted',message:String(e)};manifest.stages=manifest.stages.map((s:any)=>s.status==='running'?{...s,status:'blocked',description:row.message}:s);await Bun.write(resolve(dir,'demo.json'),JSON.stringify(manifest));await save();}})();return row;
}
